name: Test GitHub Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "✅ GitHub Actions ทำงานแล้ว!"

      - name: Show current time
        run: date

      - name: List files in repo
        run: ls -la
