name: Python Test

on: [push]  # ทำงานทุกครั้งที่ push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ติดตั้ง Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ติดตั้ง pytest
        run: pip install pytest

      - name: รัน pytest
        run: pytest
